name: System.Half

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

  # Project name to pack and publish
  PROJECT_NAME: Half

  # Official NuGet Feed settings
  NUGET_FEED: https://api.nuget.org/v3/index.json
  NUGET_KEY: ${{ secrets.NUGET_KEY }}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Generate
      # generate project each time to fit with dotnet-version
      run: dotnet new classlib --output System.Half --force
    - name: Build
      run: dotnet build System.Half  --configuration Release
    - name: Build-test
      run: dotnet build Half.Tests --configuration Release
    - name: Test
      run: dotnet test Half.Tests --no-build --verbosity normal
      # pack and publish later
    - name: Package
      run: `dotnet pack System.Half -c Release`
      
    - name: push nuget package
      run: dotnet nuget push ./System.Half/bin/Release/*.nupkg --source $NUGET_FEED --skip-duplicate --api-key $NUGET_KEY
